version: "3.9"
services:
  db:
    container_name: MySQL
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: imotodo
      MYSQL_USER: imotodo
      MYSQL_PASSWORD: imotodo
volumes:
  db-data: